### ISSUE TITLE
Fails to build with Ruby 2.2.1

### ISSUE THREAD

**Issue by Ghassan** [SciRuby/rb-gsl#11]
I downloaded the gem and when I run 
sudo ruby setup.rb I get:

setup.rb:283: warning: duplicated key at line 284 ignored: "bin-dir"
setup.rb:788:in `load_rbconfig': uninitialized constant Config (NameError)
	from setup.rb:768:in `invoke'
	from setup.rb:1578:in `<main>'

Any clues or ides why is this happening? I installed gsl 1.15 on my OSX Yosemite. Help is warmly appreciated please?

**Comment by ktns** [comment]
setup.rb is very old, and probably not maintained anymore.
Use rubygems instead.
Rubygems is bundled with ruby 1.9 or later.

**Comment by agarie** [comment]
We probably should remove setup.rb.
