### ISSUE TITLE
mark this repository as obsolete

### ISSUE THREAD

**Issue by minad** [SciRuby/rb-gsl#18]
I will merge the nmatrix specific changes to blackwinter/rb-gsl

**Comment by blackwinter** [comment]
For the record, I would like to see the canonical repository under the SciRuby organization. It's a bit unfortunate that they share the same name while it's probably too much of a hassle to make a clean merge. But if you're willing to disturb existing clones or maybe adopt a new name for the repo, I'd be happy to transfer ownership.

**Comment by minad** [comment]
yes, I will do that at some point. @mohawkjohn Could I get access to this repository too?

I will try to merge both rb-gsl and gsl gem, and we can continue the development here based on @blackwinter's current master.
