### ISSUE TITLE
Tests are failing on all Debian release architectures except for amd64

### ISSUE THREAD

**Issue by rbalint** [SciRuby/rb-gsl#22]
Please see the original bug report at:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=798535

Updated build log with 1.16.0.6:
http://debomatic-i386.debian.net/distribution#unstable/ruby-gsl/1.16.0.6+dfsg1-1/buildlog

...
Failure: test_dht3(DhtTest)
dht_test.rb:54:in `test_dht3'
     51: 
     52:     vout = dht.apply(vin)
     53: 
  => 54:     assert_equal 0.18148296716239096,   vout[0]
     55:     assert_equal 0.35680451269699853,   vout[5]
     56:     assert_equal 0.21101009980456306,   vout[10]
     57:     assert_equal 0.02892068100516861,   vout[35]
<0.18148296716239096> expected but was
<0.18148296716239112>

diff:
? 0.18148296716239096
# ?                 112
# F

...

**Comment by v0dro** [comment]
We need change the assertions to `assert_in_delta` because of precision issues.

**Comment by rbalint** [comment]
This issue is fixed in 2.1.0.1.
