### ISSUE TITLE
gsl-2.1 breaks rb-gsl

### ISSUE THREAD

**Issue by 0-wiz-0** [SciRuby/rb-gsl#24]
The latest rb-gsl release does not build against the current gsl 2.1 release. I see:

````
histogram.c: In function 'rb_gsl_histogram_fit_gaussian':
histogram.c:1222:23: error: 'gsl_multifit_fdfsolver' has no member named 'J'
   gsl_multifit_covar(s->J, 0.0, covar);
                       ^
histogram.c: In function 'rb_gsl_histogram_fit_rayleigh':
histogram.c:1356:23: error: 'gsl_multifit_fdfsolver' has no member named 'J'
   gsl_multifit_covar(s->J, 0.0, covar);
                       ^
histogram.c: In function 'rb_gsl_histogram_fit_xexponential':
histogram.c:1492:23: error: 'gsl_multifit_fdfsolver' has no member named 'J'
   gsl_multifit_covar(s->J, 0.0, covar);
                       ^
````

**Comment by ian-abbott** [comment]
There are also some warnings when compiling `sf_ellint.c` due to unused argument `n` (argument 3) being removed from `gsl_sf_ellint_D()` and `gsl_sf_ellint_D_e()` in GSL 2:

    compiling ../../../../ext/gsl_native/sf_ellint.c
    ../../../../ext/gsl_native/sf_ellint.c: In function ‘rb_gsl_sf_ellint_D’:
    ../../../../ext/gsl_native/sf_ellint.c:85:37: warning: passing argument 1 of ‘rb_gsl_sf_eval_double3_m’ from incompatible pointer type [-Wincompatible-pointer-types]
         return rb_gsl_sf_eval_double3_m(gsl_sf_ellint_D, argv[0], argv[1], argv[2],
                                         ^
    In file included from ../../../../ext/gsl_native/sf_ellint.c:13:0:
    ../../../../ext/gsl_native/include/rb_gsl_sf.h:58:7: note: expected ‘double (*)(double,  double,  double,  gsl_mode_t) {aka double (*)(double,  double,  double,  unsigned int)}’ but argument is of type ‘double (*)(double,  double,  gsl_mode_t) {aka double (*)(double,  double,  unsigned int)}’
     VALUE rb_gsl_sf_eval_double3_m(double (*func)(double, double, double, gsl_mode_t),
           ^
    ../../../../ext/gsl_native/sf_ellint.c:88:37: warning: passing argument 1 of ‘rb_gsl_sf_eval_double3_m’ from incompatible pointer type [-Wincompatible-pointer-types]
         return rb_gsl_sf_eval_double3_m(gsl_sf_ellint_D, argv[0], argv[1], argv[2],
                                         ^
    In file included from ../../../../ext/gsl_native/sf_ellint.c:13:0:
    ../../../../ext/gsl_native/include/rb_gsl_sf.h:58:7: note: expected ‘double (*)(double,  double,  double,  gsl_mode_t) {aka double (*)(double,  double,  double,  unsigned int)}’ but argument is of type ‘double (*)(double,  double,  gsl_mode_t) {aka double (*)(double,  double,  unsigned int)}’
     VALUE rb_gsl_sf_eval_double3_m(double (*func)(double, double, double, gsl_mode_t),
           ^
    ../../../../ext/gsl_native/sf_ellint.c: In function ‘rb_gsl_sf_ellint_D_e’:
    ../../../../ext/gsl_native/sf_ellint.c:95:37: warning: passing argument 1 of ‘rb_gsl_sf_eval_e_double3_m’ from incompatible pointer type [-Wincompatible-pointer-types]
       return rb_gsl_sf_eval_e_double3_m(gsl_sf_ellint_D_e, phi, k, n, m);
                                         ^
    In file included from ../../../../ext/gsl_native/sf_ellint.c:13:0:
    ../../../../ext/gsl_native/include/rb_gsl_sf.h:54:7: note: expected ‘int (*)(double,  double,  double,  gsl_mode_t,  gsl_sf_result *) {aka int (*)(double,  double,  double,  unsigned int,  struct gsl_sf_result_struct *)}’ but argument is of type ‘int (*)(double,  double,  gsl_mode_t,  gsl_sf_result *) {aka int (*)(double,  double,  unsigned int,  struct gsl_sf_result_struct *)}’
     VALUE rb_gsl_sf_eval_e_double3_m(int (*func)(double, double, double, gsl_mode_t, gsl_sf_result*),
           ^

**Comment by v0dro** [comment]
New gsl 2.1.0 has been released.
