### ISSUE TITLE
Support latest GSL release

### ISSUE THREAD

**Issue by v0dro** [SciRuby/rb-gsl#25]
GSL v2.1 has [just been released](http://www.gnu.org/software/gsl/). The current rb-gsl is not working with it, which it should ( #24 ).

Question for @blackwinter @minad : Should we maintain backwards compatibility for pre-2.1 GSL versions or force the user to upgrade?

I'd say no need for backward compatibility. What are your views?

**Comment by minad** [comment]
we already dropped ancient versions. however I think 1.16 is still widely deployed

**Comment by rbalint** [comment]
Debian has migrated to GSL 2.x in unstable making ruby-gsl package unusable due to this bug. :-(
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804499

**Comment by rbalint** [comment]
Without GSL2.x support ruby-gsl won't be released as part of next Debian stable. :-(

**Comment by v0dro** [comment]
I'm on it. Will be releasing a new version with GSL 2.x support by March first/second week.

**Comment by v0dro** [comment]
#33
