### ISSUE TITLE
Problem installing gsl without narray

### ISSUE THREAD

**Issue by michelboaventura** [SciRuby/rb-gsl#29]
Hi,

I'm trying to install gsl without narray, but it seems like it is implicitly required. During install of the gem, I get this: ```checking for narray.h... no```, which is correct. But then I get:
```
.../5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -l:narray.so
collect2: error: ld returned 1 exit status
Makefile:254: recipe for target 'gsl_native.so' failed
make: *** [gsl_native.so] Error 1
ERROR:  Error installing gsl:
        ERROR: Failed to build gem native extension.
```

It seems that ```extconf.rb``` always includes narray as a dependency.

If I change
```Ruby
gsl_gem_config('narray', 'src')

have_header('narray.h')
have_library('narray') if RUBY_PLATFORM =~ /cygwin|mingw/
```
to
```Ruby
if have_header('narray.h')
  gsl_gem_config('narray', 'src')
  have_library('narray') if RUBY_PLATFORM =~ /cygwin|mingw/
end
```

everything works fine.

**Comment by v0dro** [comment]
Do you have an environment variable `NARRAY=1`? If so please remove it.

**Comment by michelboaventura** [comment]
I don't have ``NARRAY=1``. Looking further the problem seems to be that my ``LDFLAGS`` is defined as ``L. -Wl,-O1 -Wl,--as-needed -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,--no-undefined``, so the above is true and ``narray.so`` is added:
```Ruby
$LOCAL_LIBS += " -l:#{target}.so" if arg_config("--force-link-#{target}")   ||
                                     $CFLAGS.include?('-Wl,--no-undefined') ||
                                     $LDFLAGS.include?('-Wl,--no-undefined')
```

I'm using Gentoo Linux, don't know if it is relevant. Thanks

**Comment by v0dro** [comment]
Could you also tell your version of Ruby? Cuz it works fine on my PC without NArray.

**Comment by michelboaventura** [comment]
Sure:
```
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
gcc (Gentoo 5.3.0 p1.0, pie-0.6.5) 5.3.0
gsl 1.16
```

**Comment by v0dro** [comment]
That's weird, it's working perfectly find on my PC without narray:

```
➜  ~  gem install rb-gsl 
Fetching: gsl-1.16.0.6.gem (100%)
Building native extensions.  This could take a while...
gsl can be installed with or without narray support. Please install narray before and reinstall gsl if it is missing.
Successfully installed gsl-1.16.0.6
Fetching: rb-gsl-1.16.0.6.gem (100%)
rb-gsl has been replaced by gsl
Successfully installed rb-gsl-1.16.0.6
Parsing documentation for gsl-1.16.0.6
Installing ri documentation for gsl-1.16.0.6
Parsing documentation for rb-gsl-1.16.0.6
Installing ri documentation for rb-gsl-1.16.0.6
Done installing documentation for gsl, rb-gsl after 7 seconds
2 gems installed
➜  ~  gem list | grep narray
➜  ~  ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [i686-linux]
```

Could you please make those modifications to your installation for now? Let this bug remain, we'll see if anyone else gets it too.

**Comment by v0dro** [comment]
Things should work fine with gsl 2.1.0. Can you please confirm and close the issue if its working fine?

**Comment by michelboaventura** [comment]
It worked @v0dro! Thank you very much
