### ISSUE TITLE
Strange Git history

### ISSUE THREAD

**Issue by mvz** [SciRuby/rb-gsl#3]
The git history of this repository is rather strange, having basically two roots. Perhaps it would be best to rebase the changes for moving from NArray to NMatrix onto david-macmahon/rb-gsl's master branch, or alternatively, create a branch off some older commit in that repository.

I have some experience rewriting git history, would you be interested in such a change?

**Comment by mvz** [comment]
Hi @minad, I'm not sure how that commit fixes this issue?

**Comment by minad** [comment]
This is not fixed, but I don't consider the git history important. From now on it will be consistent.

If you are interested in the history, then go to:

* https://github.com/david-macmahon/rb-gsl
* https://github.com/blackwinter/rb-gsl
* https://github.com/SciRuby/rb-gsl/tree/old-gsl-nmatrix-master

**Comment by minad** [comment]
But as @mohawkjohn said, if you want to rewrite current master based on @david-macmahon's repository, I would gladly accept such a pull request.
